### ISSUE TITLE
Compatibility with Advanced Custom Fields

### ISSUE THREAD

**Issue by jonarnes** [imgeng/image-cdn-wordpress#26]
As a Wordpress user, when using a Wordpress with the [Advanced Custom Fields](https://www.advancedcustomfields.com/) plugin, image urls are not caught by the ImageEngine plugin.

I'd like the plugin to catch and rewrite image urls provided in ACF [image type fields](https://www.advancedcustomfields.com/resources/image/) and [gallery](https://www.advancedcustomfields.com/resources/gallery/) so that valid ImageEngine urls are output on the website as well as through the WP API.

Acceptance criteria:
Images uploaded with ACF in a ACF image and gallery field gets referenced with the ImageEngine delivery address both on the website and through the API. 
![image](https://user-images.githubusercontent.com/556263/199182614-27c6dc2b-43f0-4826-91f0-dbffe948baae.png)

**Comment by kamermans** [comment]
Here's where I originally handled this:
https://github.com/imgeng/image-cdn-wordpress/blob/master/imageengine/class-imagecdn.php#L272

I wonder if the fields in the screenshot above are showing text fields with URLs in them instead of image fields?
